### ISSUE TITLE
Repeating styles

### ISSUE THREAD

**Issue by jim-rosales** [gringosim/prj-rev-bwfs-dasmoto#4]
When writing CSS rules, it's best to take a moment and analyze if any of your elements share any similarities in regards to style.  

In this case, you have three elements that share these styles (brushes, frames, paint):

```CSS
font-family: Helvetica; /** All you elements share this font **/
font-size: 32px;
font-weight: bold;
color: white;
```

Considering this it's better to take this approach:
```CSS
h2 {
  /** font-family: Helvetica; see the approach below for applying the font **/ 
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#paint {
  background-color: skyblue;
}

#brushes {
  background-color: mediumspringgreen;
}

#frames {
  background-color: lightcoral;
}

```

This way all you h2s will inherit the styles they all share and then you can apply the unique color they have separately.

As for the font, you can apply it to all your elements using the `html` selector, and then all your elements will inherit the font.

```CSS
html {
  font-family: Helvetica, serif; /** You should also include a fallback font **/
}
```

https://github.com/gringosim/prj-rev-bwfs-dasmoto/blob/d574703da8afe0746e4707f0f4445d6a4f140e23/Dasmoto/resources/CSS/style.css#L9-L15
